import { Shield, Users, Gamepad2, Building, Wifi, Mail, Clock } from "lucide-react"
import type { PasswordTemplate } from "@/types/password"

export const PASSWORD_TEMPLATES: PasswordTemplate[] = [
  {
    id: "banking",
    name: "Banking & Finance",
    description: "Maximum security for financial accounts",
    icon: <Shield className="h-4 w-4" />,
    securityLevel: "High",
    useCase: "Banks, investment accounts, payment services",
    options: {
      length: 20,
      includeUppercase: true,
      includeLowercase: true,
      includeNumbers: true,
      includeSymbols: true,
      excludeSimilar: true,
    },
  },
  {
    id: "social",
    name: "Social Media",
    description: "Balanced security for social platforms",
    icon: <Users className="h-4 w-4" />,
    securityLevel: "Medium",
    useCase: "Facebook, Twitter, Instagram, LinkedIn",
    options: {
      length: 14,
      includeUppercase: true,
      includeLowercase: true,
      includeNumbers: true,
      includeSymbols: false,
      excludeSimilar: false,
    },
  },
  {
    id: "gaming",
    name: "Gaming",
    description: "User-friendly for gaming platforms",
    icon: <Gamepad2 className="h-4 w-4" />,
    securityLevel: "Medium",
    useCase: "Steam, PlayStation, Xbox, gaming accounts",
    options: {
      length: 12,
      includeUppercase: true,
      includeLowercase: true,
      includeNumbers: true,
      includeSymbols: false,
      excludeSimilar: true,
    },
  },
  {
    id: "corporate",
    name: "Work & Corporate",
    description: "Policy-compliant for business accounts",
    icon: <Building className="h-4 w-4" />,
    securityLevel: "High",
    useCase: "Office 365, corporate systems, work accounts",
    options: {
      length: 16,
      includeUppercase: true,
      includeLowercase: true,
      includeNumbers: true,
      includeSymbols: true,
      excludeSimilar: false,
    },
  },
  {
    id: "wifi",
    name: "WiFi & Network",
    description: "Device-compatible for network access",
    icon: <Wifi className="h-4 w-4" />,
    securityLevel: "Medium",
    useCase: "WiFi passwords, router access, network devices",
    options: {
      length: 16,
      includeUppercase: true,
      includeLowercase: true,
      includeNumbers: true,
      includeSymbols: false,
      excludeSimilar: true,
    },
  },
  {
    id: "email",
    name: "Email",
    description: "Secure yet memorable for email accounts",
    icon: <Mail className="h-4 w-4" />,
    securityLevel: "Medium",
    useCase: "Gmail, Outlook, Yahoo, email providers",
    options: {
      length: 14,
      includeUppercase: true,
      includeLowercase: true,
      includeNumbers: true,
      includeSymbols: true,
      excludeSimilar: false,
    },
  },
  {
    id: "temporary",
    name: "Quick & Temporary",
    description: "Fast generation for temporary use",
    icon: <Clock className="h-4 w-4" />,
    securityLevel: "Basic",
    useCase: "Test accounts, temporary access, quick setup",
    options: {
      length: 10,
      includeUppercase: true,
      includeLowercase: true,
      includeNumbers: true,
      includeSymbols: false,
      excludeSimilar: false,
    },
  },
]
